CREATE table currency
	(SERIALNUMBER INT, 
	 FROMSYMBOL VARCHAR(10),
	 TOSYMBOL VARCHAR(10), 
	 LAST VARCHAR(50), 
	 HIGH VARCHAR(50), 
	 LOW VARCHAR(50), 
	 CHNGE VARCHAR(50), 
	 CHANGEPERCENT VARCHAR(50), 
	 PRICEDATE TIMESTAMP );
